name: shimmer
description: A package provides an easy way to add shimmer effect in Flutter project
version: 3.0.0
repository: https://github.com/Svet-00/flutter_shimmer
issue_tracker: https://github.com/Svet-00/flutter_shimmer/issues
contributors: Gregor Weber <The-Redhat>, Vasilliy Ditsyask <vasilich6107>, Svetozar Volkov
homepage: https://github.com/Svet-00/flutter_shimmer
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^1.9.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
